datasets:
  - name: hprc_v2_0_mc_grch38
    enabled: true
    builder: gfa_gz
    urls:
      - https://human-pangenomics.s3.amazonaws.com/pangenomes/freeze/release2/minigraph-cactus/hprc-v2.0-mc-grch38.gfa.gz

  - name: hprc_v2_0_mc_grch38_chrX
    enabled: true
    builder: vg
    urls:
      - https://human-pangenomics.s3.amazonaws.com/pangenomes/scratch/2025_02_28_minigraph_cactus/hprc-v2.0-mc-grch38/hprc-v2.0-mc-grch38.chroms/chrX.vg

  - name: hprc_v1_1_mc_grch38
    enabled: true
    builder: gbz
    urls:
      - https://s3-us-west-2.amazonaws.com/human-pangenomics/pangenomes/freeze/freeze1/minigraph-cactus/hprc-v1.1-mc-grch38/hprc-v1.1-mc-grch38.gbz

  # ---------------------------------------------------------------------------
  # pggb precomputed pangenome graphs from Zenodo .gfa.zst
  # ---------------------------------------------------------------------------
  
  - name: ecoli50
    enabled: true
    builder: gfa_zst
    urls:
      - https://zenodo.org/records/7937947/files/ecoli50.gfa.zst?download=1


  - name: primates_chr6
    enabled: true
    builder: gfa_zst
    urls:
      - 'https://zenodo.org/records/7937947/files/primates14.chr6.fa.gz.667b9b6.c2fac19.ee137be.smooth.final.gfa.zst?download=1'

  # ---------------------------------------------------------------------------
  # pggb pangenome graphs from Zenodo .fa.gz
  # ---------------------------------------------------------------------------

  - name: mouse17_chr19
    enabled: true
    builder: pggb_from_fasta
    urls:
      - "https://zenodo.org/records/7937947/files/mouse17.chr19.fa.gz?download=1"
    pggb:
      extra_opts: "-n 17"

  - name: tomato23_chr2
    enabled: true
    builder: pggb_from_fasta
    urls:
      - "https://zenodo.org/records/7937947/files/tomato23.chr2.fa.gz?download=1"
    pggb:
      extra_opts: "-n 23"

  # ---------------------------------------------------------------------------
  # Ultrabubble datasets via vg_from_vcf
  # ---------------------------------------------------------------------------

  - name: Ultrabubble_dataset_chr1
    enabled: true
    builder: vg_from_vcf
    urls:
      fa_gz: https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/human_g1k_v37.fasta.gz
      vcf_gz: https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr1.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz
    vg:
      region: "1"
      max_node_length: 3000000

  - name: Ultrabubble_dataset_chr10
    enabled: true
    builder: vg_from_vcf
    urls:
      fa_gz: https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/human_g1k_v37.fasta.gz
      vcf_gz: https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr10.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz
    vg:
      region: "10"
      max_node_length: 3000000
   
  - name: Ultrabubble_dataset_chr22
    enabled: true
    builder: vg_from_vcf
    urls:
      fa_gz: https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/human_g1k_v37.fasta.gz
      vcf_gz: https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr22.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz
    vg:
      region: "22"
      max_node_length: 3000000

  # ---------------------------------------------------------------------------
  # Manually built DBGs
  # ---------------------------------------------------------------------------

  # - name: M_xanthus_DBG
  #   enabled: true
  #   builder: ggcat_from_fasta
  #   urls:
  #     listings:
  #       - https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/012/685/GCA_000012685.1_ASM1268v1/
  #       - https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/278/585/GCA_000278585.2_ASM27858v2/
  #       - https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/340/515/GCA_000340515.1_Myxococcus_xanthus_DZF1/
  #       - https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/006/400/955/GCA_006400955.1_ASM640095v1/
  #       - https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/006/401/215/GCA_006401215.1_ASM640121v1/
  #       - https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/006/401/635/GCA_006401635.1_ASM640163v1/
  #       - https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/006/402/015/GCA_006402015.1_ASM640201v1/
  #       - https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/006/402/735/GCA_006402735.1_ASM640273v1/
  #       - https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/006/402/735/GCA_006402735.1_ASM640273v1/
  #       - https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/900/106/535/GCA_900106535.1_IMG-taxon_2693429903_annotated_assembly/
  #     origin: https://ftp.ncbi.nlm.nih.gov
  #     pattern: '.*\.fna\.gz$'
  #   ggcat:
  #     k: 41