software:
  biopath:
    repo: https://github.com/sebschmi/biopath
    version: 14342d245fffef823441797141372bee68b3653c

  BubbleFinder:
    repo: https://github.com/sebschmi/BubbleFinder
    version: 5a26837691fd01baaa6df62d1c5cb2dc746882a4